
name: Release
on:
  push:
    branches:
      - "master"


jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        product: ['firefox', 'firefox-beta', 'firefox-esr', 'firefox-nightly', 'firefox-devedition']
    env:
      FIREFOX_PRODUCT: ${{ matrix.product }}
      FIREFOX_OS: 'linux64'
      FIREFOX_LANG: 'en-US'
    steps:
    - uses: actions/checkout@v2
      

    - name: Build ${{ matrix.product }}
      run: |
        bash build/build.sh
        echo "$FIREFOX_VERSION.r$FIREFOX_BUILD_ID"

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.product }}-continuous.AppImage
        path: 'dist'

    - name: Release Tagged
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: ${{ matrix.product }} v${{ env.FIREFOX_VERSION }}.r${{ env.FIREFOX_BUILD_ID }}
        automatic_release_tag: ${{ env.FIREFOX_PRODUCT }}-v${{ env.FIREFOX_VERSION }}.r${{ env.FIREFOX_BUILD_ID }}
        prerelease: true
        draft: false 
        files: |
          dist
        repo_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release Continuous
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: Latest Continous build for ${{ matrix.product }} v${{ env.FIREFOX_VERSION }}.r${{ env.FIREFOX_BUILD_ID }}
        automatic_release_tag: ${{ env.FIREFOX_PRODUCT }}
        prerelease: false
        draft: false 
        files: |
          dist
        repo_token: ${{ secrets.GITHUB_TOKEN }}
